### ISSUE TITLE
PVDD and AVDD must be the same voltage (or else TPA2012 AMP runs hot)

### ISSUE THREAD

**Issue by technobly** [adafruit/Adafruit-Music-Maker-FeatherWing-PCB#1]
Hi Adafruit!

I found and fixed a design issue with the "Adafruit VS1053 Amp FeatherWing" version of this FeatherWing.

I had a brand new one of these with the TPA2012 Class-D amplifier and the volume was super low no matter what I did to adjust it.  I felt the TPA2012 AMP and it was blazing hot to the touch.  I figured I killed it with ESD at some point in the past, so I ordered a replacement amp from Digikey.  After swapping it out I had the same issue!

I searched your forums for this and found many people with the same problem, and no resolution as far as I could see:

Search For "amp hot"
https://forums.adafruit.com/search.php?st=0&sk=t&sd=d&sr=posts&keywords=amp+hot&start=75

And find many pages of these:
https://forums.adafruit.com/viewtopic.php?t=136709&hilit=amp+hot
https://forums.adafruit.com/viewtopic.php?t=191462&hilit=amp+hot
https://forums.adafruit.com/viewtopic.php?t=185623&hilit=amp+hot
https://forums.adafruit.com/viewtopic.php?t=181647&hilit=amp+hot
https://forums.adafruit.com/viewtopic.php?t=178464&hilit=amp+hot
https://forums.adafruit.com/viewtopic.php?t=171458&hilit=amp+hot
https://forums.adafruit.com/viewtopic.php?=169776&hilit=amp+hot
https://forums.adafruit.com/viewtopic.php?t=167124&hilit=amp+hot
https://forums.adafruit.com/viewtopic.php?t=166540&hilit=amp+hot
https://forums.adafruit.com/viewtopic.php?t=165319&hilit=amp+hot
https://forums.adafruit.com/viewtopic.php?t=156650&hilit=amp+hot
https://forums.adafruit.com/viewtopic.php?t=144562&hilit=amp+hot
https://forums.adafruit.com/viewtopic.php?t=143768&hilit=amp+hot
...

One thing I see support asking a lot is if customers accidentally short-circuited the speaker outputs.  It seems like this chip has necessary protections for that.
![Screen Shot 2022-07-23 at 8 38 38 PM](https://user-images.githubusercontent.com/2249224/180628649-8efd5f02-e34f-48c1-a116-220c1cf5bafa.png)

The TPA2012 Datasheet: https://www.ti.com/lit/ds/symlink/tpa2012d2.pdf

Shows that the PVDD and AVDD "must be the same voltage"
![Screen Shot 2022-07-23 at 4 51 23 PM](https://user-images.githubusercontent.com/2249224/180623992-3295d8b6-3d58-48ee-b6fd-e06fc9426081.png)

The reference design shows both inputs tied together, sharing 10uF and 1uF
![Screen Shot 2022-07-23 at 4 52 49 PM](https://user-images.githubusercontent.com/2249224/180624058-6f79df6b-caa1-457d-8ea5-ab7d91911b5c.png)

TI references "PVDD/AVDD" together as one input:
![Screen Shot 2022-07-23 at 4 54 50 PM](https://user-images.githubusercontent.com/2249224/180624102-73ff9e8a-b2f4-4853-a8a6-a8dd5979abd3.png)

However, on the Music Maker FeatherWing, the AVDD input is tied to 3.3V and does not have as much filtering/decoupling capacitance on it as PVDD does.
![Screen Shot 2022-07-23 at 4 56 31 PM](https://user-images.githubusercontent.com/2249224/180624149-a3cc0685-e261-4b04-bb55-e0165b3f932e.png)

It's pretty easy to modify the PCB to remove AVDD from 3.3V and jumper the AVDD input to PVDD like so:
![IMG_3360](https://user-images.githubusercontent.com/2249224/180624235-b8e9b189-88c6-4902-96ac-b686f8cb36cc.JPG)

After doing this mod, my TPA2012 chip is not even warm at full volume and max gain (both G0 and G1 jumpered) with a single 8 ohm speaker.

~The volume is still something to be desired, but with a proper enclosure around the speaker it's much fuller and louder.~
EDIT: Solved this one as well, see #2 

Other products that use the TPA2012 or TPA2016 should be looked at as well.  I've seen other forum posts about these being hot unexpectedly as well.

Hope this is helpful :D 
Best regards,
Brett Walach

**Comment by ladyada** [comment]
iiiiiiiiiiiiiiiinteresting. and yes, totally true! the odd thing about the overheating issue is we could never reproduce the issue - the boards we built were fine, so it seems like it didnt always trigger the overheating.

ive done a quick revision to make rev D: AVDD still exists but is only used by the VS1053 - the TPA has only PVDD connected and gets both capacitors
check it out & we can replace the current stock of boards/pcbs with this new design :)

[VS1053 Amp Wing Rev D.zip](https://github.com/adafruit/Adafruit-Music-Maker-FeatherWing-PCB/files/9185056/VS1053.Amp.Wing.Rev.D.zip)

**Comment by technobly** [comment]
@ladyada LGTM!  Super fast turnaround 😸

**Comment by ladyada** [comment]
forgot to update - this was implemented

**Comment by ZevEisenberg** [comment]
I have a Music Maker with amp that I think has a similar problem. The volume isn't too low, but the amp chip gets super hot, even when audio isn't playing. I bought it in February 2023, but via [this Amazon listing](https://www.amazon.com/gp/product/B07BB7LZRJ/) because Adafruit didn't (and doesn't) have them in stock. Is my board affected? Is it something to worry about? I'm 3D printing an enclosure, so I'm kind of worried about the heat just in terms of not wanting to melt the box it's in 😅

![IMG_2860](https://user-images.githubusercontent.com/464574/226232297-8dbedf5f-8b75-4b11-ad3e-70198c05ebfd.jpeg)

Wiring setup and [speaker](https://www.amazon.com/gp/product/B08JCHK7GR):

![IMG_2859](https://user-images.githubusercontent.com/464574/226232345-ff02b1a6-d102-4b4b-8175-58edf7f6b010.jpeg)

**Comment by technobly** [comment]
@ZevEisenberg you can probably make the same modification (cut and jump) I show up above to fix it.  You'll need some good lighting and magnification though.

**Comment by ZevEisenberg** [comment]
That's a little above my pay grade, I suspect. I ended up ordering a new one. I don't think I have miniature-enough equipment in my novice setup. Perhaps some day.

**Comment by technobly** [comment]
You could probably do it with a $5 jeweler's loupe and x-acto knife.  I also highly recommend the [2.25x version of this LED magnifier lamp.](https://www.amazon.com/gp/product/B07MMZ27QK)  Did you order a new one from Adafruit directly? If so it should be the updated design.

**Comment by ZevEisenberg** [comment]
Yep, I did order it. Modding the board does sound fun and useful, but I'm just trying to build a music box for my daughter, and if I can throw $25 at the problem to make it go away, I'm happy! (So I can return to my regularly scheduled problem of building novel electronics and 3D printing cases.)

**Comment by ZevEisenberg** [comment]
Aha! I found the rev number. It took holding a new and old board in my hands and comparing them to spot it. It's the letter in the circle at the upper right corner of my first photo. My old board is a rev C, and the new one is rev D, so that confirms my suspicions 😁.
