### ISSUE TITLE
RIGHT channel is very quiet (low volume), incorrect R6 (should be 100 ohms)

### ISSUE THREAD

**Issue by technobly** [adafruit/Adafruit-Music-Maker-FeatherWing-PCB#2]
> Related to my other issue #1 

Yay, I figured out why it was so quiet as well!

I'm sure you've fixed this issue by now, but just in case and/or there are others out there with a quiet RIGHT channel.  Up until now I was just using the RIGHT channel and it was unusually quiet, even after the HOT fix #1.  I tried the LEFT channel by chance and about raised the dead with the volume!!  That's more like it!!

So I measured the audio signals leaving the VS1053B and the RIGHT channel seemed to attenuate to nothing right after R6.

R6 measured 100k ohms, and should be 100 ohms 😸 
NOTE: Notice the solder is original.  BTW this MusicMaker FeatherWing was probably purchased 6 year ago!
![IMG_3362](https://user-images.githubusercontent.com/2249224/180661913-f4dfda2b-2750-4721-a8b5-8dd4c69259f7.JPG)
![IMG_3363](https://user-images.githubusercontent.com/2249224/180661922-f0997ccb-b060-4287-82ea-83f92659cf92.jpg)

I replaced this incorrectly stuffed R6 with a 120 ohm I had on hand and now we are jammin' 🕺🏼 🎶 🔊

**Comment by ladyada** [comment]
kk - this issue was a pick and place error, found/resolved in 2018 (your feather is very old)
